### ISSUE TITLE
pre-load docker images

### ISSUE THREAD

**Issue by eli007s** [kwilczynski/packer-templates#3]
How would you be able to pre-load with docker images?

I notice that if i included my `docker pull` commands at the end of common/docker.sh that when the artifacts are finished, the docker images are not on the server. But in the output logs they clearly show them being pulled from the docker repositories.

Where would we be able to place the code to have these images be persistent?

thanks.

**Comment by kwilczynski** [comment]
@eli007s hi there! Apologies for the delay in getting back to you, and apologies for troubles!

Would you like the Docker images to be added to an EC2 (AMI) image or to a Vagrant box?

I believe, that the reason why the images are not included in the final product, is to do with the clean-up process. The images which are being saved are most likely also being cleaned up in due process (an effort to minimise the size of the image).

I will have a look how to ensure that you can persist the images, and I will report back to you.

**Comment by kwilczynski** [comment]
Hi @eli007s,

I am going to close this issue for now, as it's has been a very long time since it was opened. I hope you've been able to solve all the problems with the Docker images being deleted (should this not be the case, then feel free to re-open this issue again).

All the best,
Krzysztof
